#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

const NOTION_API_BASE_URL = 'https://api.notion.com/v1';
const DEFAULT_NOTION_VERSION = '2022-06-28';
const CLINICO_REVISADO_DATA_SOURCE_ID = '366da8a92980802a839ccbd8d2d7f111';
const DEFAULT_PAYLOAD_PATH = path.resolve(
  process.cwd(),
  'data',
  'generated',
  'clinical_drug_interactions',
  'notion_interaction_pairs_payload.json',
);

function loadEnvFiles() {
  const candidates = [
    path.resolve(process.cwd(), '.env'),
    path.resolve(process.cwd(), 'backend', '.env'),
  ];

  for (const filePath of candidates) {
    if (!fs.existsSync(filePath)) {
      continue;
    }

    const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/);

    for (const line of lines) {
      const trimmed = line.trim();

      if (!trimmed || trimmed.startsWith('#')) {
        continue;
      }

      const separatorIndex = trimmed.indexOf('=');

      if (separatorIndex === -1) {
        continue;
      }

      const key = trimmed.slice(0, separatorIndex).trim();
      const value = trimmed.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, '');

      if (key && process.env[key] == null) {
        process.env[key] = value;
      }
    }
  }
}

function parseArgs(argv) {
  const args = {
    payloadPath: DEFAULT_PAYLOAD_PATH,
    apply: false,
    limit: Number.POSITIVE_INFINITY,
    dataSourceId: process.env.NOTION_CLINICO_REVISADO_DATA_SOURCE_ID || CLINICO_REVISADO_DATA_SOURCE_ID,
    resolveBySlug: false,
  };

  for (let index = 2; index < argv.length; index += 1) {
    const arg = argv[index];
    const next = argv[index + 1];

    if (arg === '--payload' && next) {
      args.payloadPath = path.resolve(next);
      index += 1;
    } else if (arg === '--apply') {
      args.apply = true;
    } else if (arg === '--data-source-id' && next) {
      args.dataSourceId = next;
      index += 1;
    } else if (arg === '--resolve-by-slug') {
      args.resolveBySlug = true;
    } else if (arg === '--limit' && next) {
      args.limit = Number.parseInt(next, 10);
      index += 1;
    } else if (arg === '--help') {
      printHelp();
      process.exit(0);
    }
  }

  return args;
}

function printHelp() {
  console.log([
    'Usage: node tools/sync_clinical_drug_interactions_to_notion.js [options]',
    '',
    'Options:',
    '  --payload <path>   Payload generated by generate_clinical_drug_interactions.js.',
    '  --apply            Actually update Notion. Omit for dry run.',
    `  --data-source-id <id>  Data source/database used to resolve pages by Slug. Defaults to Clinico Revisado (${CLINICO_REVISADO_DATA_SOURCE_ID}).`,
    '  --resolve-by-slug      Resolve page IDs by Slug in the Clinico Revisado data source instead of using stale JSON page IDs.',
    '  --limit <n>        Update at most n pages, useful for smoke tests.',
    '  --help             Show this help.',
  ].join('\n'));
}

function getNotionApiKey() {
  return process.env.NOTION_CLINICO_REVISADO_TOKEN ||
    process.env.NOTION_TOKEN ||
    process.env.NOTION_API_KEY ||
    process.env.NOTION_ACCESS_TOKEN;
}

function chunkText(value, chunkSize = 1900) {
  const text = String(value || '');
  const chunks = [];

  for (let index = 0; index < text.length; index += chunkSize) {
    chunks.push(text.slice(index, index + chunkSize));
  }

  return chunks.length ? chunks : [''];
}

function buildRichText(value) {
  return chunkText(value).map((content) => ({
    type: 'text',
    text: { content },
  }));
}

function normalizeNotionId(value) {
  return String(value || '')
    .replace(/^collection:\/\//, '')
    .replace(/^database:\/\//, '')
    .replace(/-/g, '')
    .trim();
}

async function queryNotionPageBySlug({ apiKey, notionVersion, dataSourceId, slug }) {
  const normalizedDataSourceId = normalizeNotionId(dataSourceId);

  if (!normalizedDataSourceId) {
    return null;
  }

  const response = await fetch(`${NOTION_API_BASE_URL}/databases/${normalizedDataSourceId}/query`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
      'Notion-Version': notionVersion,
    },
    body: JSON.stringify({
      page_size: 1,
      filter: {
        property: 'Slug',
        rich_text: {
          equals: slug,
        },
      },
    }),
  });

  if (!response.ok) {
    const responseBody = await response.text().catch(() => '');
    const accessHint = response.status === 404
      ? ` Check whether the Clinico Revisado data source (${dataSourceId}) is shared with the Notion integration used by this token.`
      : '';
    const error = new Error(`Unable to resolve Notion page for slug ${slug}.${accessHint}`);
    error.responseBody = responseBody;
    error.status = response.status;
    throw error;
  }

  const json = await response.json();
  return Array.isArray(json.results) && json.results[0]?.id ? json.results[0].id : null;
}

async function updateNotionPage({ apiKey, notionVersion, pageId, propertyName, value }) {
  const response = await fetch(`${NOTION_API_BASE_URL}/pages/${pageId}`, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${apiKey}`,
      'Notion-Version': notionVersion,
    },
    body: JSON.stringify({
      properties: {
        [propertyName]: {
          rich_text: buildRichText(value),
        },
      },
    }),
  });

  if (!response.ok) {
    const responseBody = await response.text().catch(() => '');
    const error = new Error(`Unable to update Notion page ${pageId}`);
    error.responseBody = responseBody;
    error.status = response.status;
    throw error;
  }

  return response.json();
}

async function main() {
  loadEnvFiles();

  const args = parseArgs(process.argv);
  const payload = JSON.parse(fs.readFileSync(args.payloadPath, 'utf8'));
  const rows = Array.isArray(payload.rows) ? payload.rows.slice(0, args.limit) : [];
  const propertyName = payload.property_name || 'Interações Estruturadas';

  if (!args.apply) {
    console.log(JSON.stringify({
      dry_run: true,
      rows: rows.length,
      property_name: propertyName,
      payload: args.payloadPath,
      resolve_by_slug: args.resolveBySlug,
      data_source_id: args.dataSourceId || null,
      hint: 'Run again with --apply to update Notion.',
    }, null, 2));
    return;
  }

  const apiKey = getNotionApiKey();

  if (!apiKey) {
    throw new Error('Missing Notion API key. Set NOTION_CLINICO_REVISADO_TOKEN, NOTION_TOKEN, NOTION_API_KEY, or NOTION_ACCESS_TOKEN.');
  }

  const notionVersion = process.env.NOTION_VERSION || DEFAULT_NOTION_VERSION;
  const pageIdBySlug = new Map();
  const failures = [];
  const skipped = [];
  let updated = 0;

  for (const row of rows) {
    let pageId = row.page_id;

    try {
      if (args.resolveBySlug) {
        if (!pageIdBySlug.has(row.slug)) {
          pageIdBySlug.set(row.slug, await queryNotionPageBySlug({
            apiKey,
            notionVersion,
            dataSourceId: args.dataSourceId,
            slug: row.slug,
          }));
        }

        pageId = pageIdBySlug.get(row.slug);
      }

      if (!pageId) {
        skipped.push({
          slug: row.slug,
          reason: args.resolveBySlug ? 'slug_not_found' : 'missing_page_id',
        });
        continue;
      }

      await updateNotionPage({
        apiKey,
        notionVersion,
        pageId,
        propertyName,
        value: row.value,
      });
      updated += 1;
    } catch (error) {
      failures.push({
        page_id: row.page_id,
        slug: row.slug,
        status: error.status || null,
        error: error.message,
        responseBody: error.responseBody || '',
      });
    }
  }

  console.log(JSON.stringify({
    dry_run: false,
    requested: rows.length,
    updated,
    skipped: skipped.length,
    failed: failures.length,
    skippedRows: skipped,
    failures,
  }, null, 2));

  if (failures.length > 0) {
    process.exitCode = 1;
  }
}

main().catch((error) => {
  console.error(error.message);
  if (error.responseBody) {
    console.error(error.responseBody);
  }
  process.exitCode = 1;
});
